#ifndef OPENUPS_CONFIG_INTERNAL_H
#define OPENUPS_CONFIG_INTERNAL_H

#include "openups.h"

#define OPENUPS_DEFAULT_TARGET "1.1.1.1"
#define OPENUPS_DEFAULT_INTERVAL_SEC 10
#define OPENUPS_DEFAULT_FAIL_THRESHOLD 5
#define OPENUPS_DEFAULT_TIMEOUT_MS 2000
#define OPENUPS_DEFAULT_DELAY_MINUTES 0
#define OPENUPS_MAX_DELAY_MINUTES (365 * 24 * 60)
#define OPENUPS_DEFAULT_SYSTEMD true

#endif